before:
  hooks:
    - go mod download
    - golint ./...
builds:
  -
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
- image_templates:
  - "wincus/spot-price-exporter:latest"
  - "wincus/spot-price-exporter:{{.Version}}"
